### ISSUE TITLE
Epoch configuration

### ISSUE THREAD

**Issue by SirSykon** [xinntao/Real-ESRGAN#161]
Hi. I'm training to control the amount of epochs when finetuning but I see no option to control it in finetune_realesrgan_x4plus.yml.

Thanks!

**Comment by cliffordkleinsr** [comment]
In your yml file this value is the one you'd want to change:

```
  scheduler:
    type: MultiStepLR
    milestones: [400000] # change this
    gamma: 0.5

  total_iter: 400000 # change this
  warmup_iter: -1  # no warm up

```
