### ISSUE TITLE
RealESRGAN_x1.pth model

### ISSUE THREAD

**Issue by Jerchongkong** [xinntao/Real-ESRGAN#622]
Is there a non-compact pre-trained X1 model available? I'm trying to train a denoiser, but the pre-trained model isn't delivering complete results. I tried using the regular X4 model, which gave me decent results, but I need one that works at the original X1 resolution. Is there an X1 model available, or if not, is there a way to create one or convert the X4 model to X1?

**Comment by Jerchongkong** [comment]
I answer myself, such model doesn't exist, therefore the best way to train a model on a x1 scale is to start from scratch. The way to do this is to modify this section of the YAML code as follows:

```
# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: ~
  param_key_d: params
  strict_load_d: true
  resume_state: ~
```
